Add LiquidFreeSettings Check
Shopify/theme-tools pull request #598
Opened 2024-11-15 21:31 UTC by navdeep5

## What are you adding in this PR?

Resolves https://github.com/Shopify/theme-tools/issues/558

This PR introduces enhanced validation checks for `Settings`; specifically ensuring that they do not contain liquid logic in the format of `{% ... %}`.
![image](https://github.com/user-attachments/assets/3f90a33f-5cf1-40cc-b395-14ff433874e4)

## What's next? Any followup issues?

With this being a new check, we will want to update https://github.com/Shopify/shopify-dev so users can understand their errors. Developer Docs changes: https://github.com/Shopify/shopify-dev/pull/50841

## What did you learn?

When writing this check I thought of three different implementations that could have been used -- it is important to understand the balance of complexity and shipping fast. 

## Before you deploy

- [x] This PR includes a new checks or changes the configuration of a check
  - [x] I included a minor bump `changeset`
  - [x] It's in the `allChecks` array in `src/checks/index.ts`
  - [x] I ran `yarn build` and committed the updated configuration files
    
    
    
    - [ ] If applicable, I've updated the `theme-app-extension.yml` config

- [x] I included a minor bump `changeset`
- [x] My feature is backward compatible

- [ ] I included a patch bump `changeset`

2024-11-19 16:31 UTC, miazbikowski requested changes
🎩 
1. preset root level settings ✅ 
2. preset blocks' (first level) (as hash) settings ✅ 
3. nested preset blocks (as hash) settings ✅ 
4. preset blocks' (first level) (as array) settings ✅ 
5. nested preset blocks (as array) settings ✅

2024-11-21 15:40 UTC, navdeep5 commented on packages/theme-check-common/src/checks/liquid-free-settings/index.spec.ts
> +    });
This is what I heard too -- still seems to be up in the air. That being said, if you feel as though it makes sense to ignore it in this check, we can proceed with that.

2024-11-21 19:01 UTC, albchu commented on packages/theme-check-common/src/checks/liquid-free-settings/index.ts
> +              const value = schemaNode.value.value;
Nit: You could destructure both `value` and `loc` out of `schemaNode.value` so your message indicies could read a bit more concise down the line.
```suggestion
              const {value, loc} = schemaNode.value.value;
```

2024-11-21 19:02 UTC, albchu approved these changes

2024-11-21 21:41 UTC, navdeep5 commented on packages/theme-check-common/src/checks/liquid-free-settings/index.spec.ts
> +    });
After chatting with @stephanie-shopify, `available_if` is up in the air and could be altered at any time, so for safe being, we will ignore liquid in `available_if`.

2024-11-25 16:30 UTC, charlespwd approved these changes

2024-11-26 13:43 UTC, merged